version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_futbol
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: futbol
      MYSQL_USER: futbol_user
      MYSQL_PASSWORD: futbol_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
